apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
metadata:
  name: app-secret
  labels:
    app: hive-metastore
