apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
  selector:
    io.kompose.service: hive-metastore
