apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\System32\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: hive-metastore
    spec:
      containers:
        - env:
            - name: DB_DRIVER
              value: postgres
            - name: SERVICE_NAME
              value: metastore
            - name: SERVICE_OPTS
              value: |
                -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                -Djavax.jdo.option.ConnectionUserName=hive
                -Djavax.jdo.option.ConnectionPassword=password
          image: hive-metastore
          name: hive-metastore
          ports:
            - containerPort: 9083
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              name: hive-metastore-cm0
              subPath: core-site.xml
            - mountPath: /opt/hive/data/warehouse
              name: metastore
      hostname: metastore
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: core-site.xml
                path: core-site.xml
            name: hive-metastore-cm0
          name: hive-metastore-cm0
        - name: metastore
          persistentVolumeClaim:
            claimName: metastore
