apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mc
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mc
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\System32\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mc
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' until (/usr/bin/mc config host add minio http://minio:9000 user password) do echo ''...waiting...'' && sleep 1; done; /usr/bin/mc rm -r --force minio/iris; /usr/bin/mc mb minio/iris; /usr/bin/mc policy set public minio/iris; exit 0; '
          image: minio/mc
          name: mc
      restartPolicy: Always
