apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: metastore
  name: metastore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
